name: Plugin Check

on:
    pull_request:
    push:
      branches:
      - main

permissions:
    contents: read

env:
    PLUGIN_SLUG: "viktors-consent-tracking-guard-for-wordpress"

jobs:
    plugin-check:
        name: Plugin Check
        runs-on: ubuntu-latest
        steps:
        -
            name: "Check out repository"
            uses: "actions/checkout@v6"
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "7.4"
                coverage: "none"
        -
            name: "Checkout repository"
            uses: "actions/checkout@v6"
        -
            name: "Install development dependencies"
            run: "composer install --no-interaction --prefer-dist --no-dev"
        -
            name: Build plugin
            run: |
                mkdir -p "dist/${PLUGIN_SLUG}"
                rsync --archive --include-from=.distinclude --exclude='*' ./ "dist/${PLUGIN_SLUG}/"
        -
            name: Run Plugin Check
            uses: wordpress/plugin-check-action@v1
            with:
              build-dir: "dist/${{ env.PLUGIN_SLUG }}"
              repo-token: ''
