name: Plugin Check

on:
    pull_request:
    push:
      branches:
      - main

permissions:
    contents: read

jobs:
    plugin-check:
        name: Plugin Check
        runs-on: ubuntu-latest
        steps:
        -
            name: "Check out repository"
            uses: "actions/checkout@v6"
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@v2"
            with:
                php-version: "7.4"
                coverage: "none"
        -
            name: "Checkout repository"
            uses: "actions/checkout@v6"
        -
            name: "Install development dependencies"
            run: "composer install --no-interaction --prefer-dist --no-dev"
        -
            name: Build plugin
            run: |
                mkdir -p build/viktors-consent-tracking-guard
                cp -r viktors-consent-tracking-guard.php composer.json readme.txt wpml-config.xml assets languages src vendor build/viktors-consent-tracking-guard/
        -
            name: Run Plugin Check
            uses: wordpress/plugin-check-action@v1
            with:
              build-dir: build/viktors-consent-tracking-guard
              repo-token: ''
